from __future__ import annotations

import math
import random
from atlas_math.modules.shared.common import make_sample

MODULE_INFO = {
    "module_id": "linear_algebra.vector_spaces.span",
    "name": "Span of Vectors",
    "topic": "linear_algebra",
    "subtopic": "vector_spaces.span",
    "difficulty_levels": ["level_1", "level_2", "level_3", "level_4", "level_5"],
    "enabled": True,
}

INSTRUCTION_TEMPLATES = ['Describe the span requested in {problem}. Decide whether the listed vectors span the whole target space, a line, or a plane, and explain the conclusion.', 'Work through {problem} by interpreting span as all linear combinations of the given vectors.', 'Determine the set generated by the vectors in {problem}. Use linear combinations to classify the span.']


def _instruction(rng: random.Random, problem: str) -> str:
    return rng.choice(INSTRUCTION_TEMPLATES).format(problem=problem)



def _vec_to_str(v):
    return f"⟨{', '.join(str(x) for x in v)}⟩"

def _build_problem(rng: random.Random, difficulty: str):
    cases = [
        ([[1, 0], [0, 1]], "R^2", "the standard basis vectors generate every vector in R^2"),
        ([[1, 2], [2, 4]], "a line in R^2", "the second vector is a scalar multiple of the first, so all combinations stay on one line"),
        ([[1, 0, 0], [0, 1, 0]], "the xy-plane in R^3", "linear combinations have the form (a, b, 0)"),
        ([[1, 1, 0], [0, 1, 1], [1, 2, 1]], "a plane in R^3", "the third vector equals the sum of the first two, so the span is two-dimensional"),
    ]
    vecs, ans, reason = rng.choice(cases)
    problem = f"Describe span({_vec_to_str(vecs[0])}, {_vec_to_str(vecs[1])}" + (f", {_vec_to_str(vecs[2])}" if len(vecs) > 2 else "") + ")."
    answer = f"The span is {ans} because {reason}."
    metadata = {"vectors": vecs, "span_classification": ans}
    return problem, answer, metadata



def _build_sample(rng: random.Random, difficulty: str):
    problem, answer, metadata = _build_problem(rng, difficulty)
    return make_sample(
        module_id=MODULE_INFO["module_id"],
        topic=MODULE_INFO["topic"],
        subtopic=MODULE_INFO["subtopic"],
        difficulty=difficulty,
        instruction=_instruction(rng, problem),
        input_text=problem,
        answer=answer,
        metadata=metadata,
    )


def generate(count: int = 10, difficulty: str = "level_1", seed: int | None = None):
    rng = random.Random(seed)
    return [_build_sample(rng, difficulty) for _ in range(count)]


def iter_samples(difficulty: str = "level_1", seed: int | None = None):
    rng = random.Random(seed)
    while True:
        yield _build_sample(rng, difficulty)


def estimate_capacity():
    return None
